site_name: 植创社

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - attr_list
  - mdx_truly_sane_lists

copyright: Copyright &copy; 2025 植创社

nav:
  - 首页: index.md
  - 关于我们:
      - 组织架构: about/structure.md
      - 人员: about/staff.md
  - 作品:
      - 2026年:
          - PvZ2026新春会: works/2026.md
      - 2025年:
          - PvZ16周年庆典: works/16.md
  - 制度:
      - 社团活动章程: strategy/main.md
  - 加入我们: strategy/join-us.md
